version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"  # AMQP protocol port
      - "15672:15672"  # Management UI port
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  producer:
    build:
      context: .
      dockerfile: Dockerfile
    command: npm run start:producer
    environment:
      - RABBITMQ_URL=amqp://rabbitmq:5672
      - QUEUE_NAME=task_queue
      - LOG_LEVEL=info
    depends_on:
      - rabbitmq

  consumer:
    build:
      context: .
      dockerfile: Dockerfile
    command: npm run start:consumer
    environment:
      - RABBITMQ_URL=amqp://rabbitmq:5672
      - QUEUE_NAME=task_queue
      - LOG_LEVEL=info
    depends_on:
      - rabbitmq

volumes:
  rabbitmq_data: 